# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.1"

gem "rails", ">= 6.0.3.1"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 4.3"
gem "rack-cors"
gem "rswag-api"
gem "rswag-ui"
gem "dry-validation", "~> 1.5"
gem "brakeman", "~> 4.7"
gem "bundle-audit", "~> 0.1.0"

group :development, :test do
  gem "byebug", platforms: %i(mri mingw x64_mingw)
  gem "factory_bot_rails", "~> 4.0"
  gem "faker", "~> 2.11.0"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "rubocop", "~> 0.81.0", require: false
  gem "rubocop-rails", "~>2.4.1", require: false
  gem "rubocop-rspec", "~>1.38", require: false
end

group :test do
  gem "database_cleaner-active_record"
  gem "shoulda-matchers", "~> 4.3"
end
