---
swagger: '2.0'
info:
  title: tests_api
  version: v1.0
paths:
  "/api/tests/":
    get:
      summary: Retrieves tests
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        type: integer
        description: Number of results to return per page.
        required: false
      - name: offset
        in: query
        type: integer
        description: The initial index from which to return the results.
        required: false
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: integer
                nullable: true
              previous:
                type: integer
                nullable: true
              results:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    subject:
                      type: string
                    question:
                      type: string
                    answer:
                      type: string
            required:
            - count
            - next
            - previous
            - results
          examples:
            application/json:
              count: 10
              next: 
              previous: 
              results:
              - uuid: b77eb326-efc1-41e1-a37e-c66bcff4f340
                subject: Science
                question: Is math related to science?
                answer: Non't
  "/api/tests/{uuid}":
    get:
      summary: Retrieves a test
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        type: string
        required: true
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              uuid:
                type: string
              subject:
                type: string
              question:
                type: string
              answer:
                type: string
            required:
            - uuid
            - subject
            - question
            - answer
          examples:
            application/json:
              uuid: b77eb326-efc1-41e1-a37e-c66bcff4f340
              subject: Science
              question: Is math related to science?
              answer: Non't
        '404':
          description: not_found
          schema:
            type: object
            properties:
              detail:
                type: string
          examples:
            application/json:
              detail: Not found.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
