---
swagger: '2.0'
info:
  title: tests_api
  version: v1.0
paths:
  "/api/tests/":
    get:
      summary: Retrieves tests
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        type: integer
        required: false
        description: Number of results to return per page.
      - name: offset
        in: query
        type: integer
        required: false
        description: The initial index from which to return the results.
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                nullable: true
              previous:
                type: string
                nullable: true
              results:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    lesson_uuid:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          uuid:
                            type: string
                          question_type:
                            type: string
                          content:
                            type: string
                          choices:
                            type: array
                            items:
                              type: object
                              properties:
                                answer:
                                  type: string
                                correct:
                                  type: boolean
                              required:
                              - answer
                              - correct
                        required:
                        - uuid
                        - question_type
                        - content
                        - choices
                  required:
                  - uuid
                  - lesson_uuid
                  - title
                  - description
                  - questions
            required:
            - count
            - next
            - previous
            - results
          examples:
            application/json:
              count: 10
              next: 
              previous: 
              results:
              - uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
                lesson_uuid: cf48df3b-ae86-464e-acd7-6cdca498fa8a
                title: Accusantium
                description: Similique aliquam voluptas quia.
                questions:
                - uuid: 95639f83-9600-4637-903a-c5b08d2f4e7c
                  question_type: binary
                  content: Voluptate repellat ut deserunt?
                  choices:
                  - answer: totam
                    correct: true
                  - answer: est
                    correct: false
    post:
      summary: Creates a test
      tags:
      - Tests
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: payload
        in: body
        schema:
          type: object
          properties:
            lesson_uuid:
              type: string
            title:
              type: string
            description:
              type: string
            questions:
              type: array
              items:
                type: object
                properties:
                  question_type:
                    type: string
                  content:
                    type: string
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        answer:
                          type: string
                        correct:
                          type: boolean
                      required:
                      - answer
                      - correct
                required:
                - question_type
                - content
                - choices
          required:
          - lesson_uuid
          - title
          - description
          - questions
      responses:
        '201':
          description: created
          schema:
            type: object
            properties:
              uuid:
                type: string
              lesson_uuid:
                type: string
              title:
                type: string
              description:
                type: string
              questions:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    question_type:
                      type: string
                    content:
                      type: string
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          answer:
                            type: string
                          correct:
                            type: boolean
                        required:
                        - answer
                        - correct
                  required:
                  - uuid
                  - question_type
                  - content
                  - choices
            required:
            - uuid
            - lesson_uuid
            - title
            - description
            - questions
          examples:
            application/json:
              uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
              lesson_uuid: cf48df3b-ae86-464e-acd7-6cdca498fa8a
              title: Accusantium
              description: Similique aliquam voluptas quia.
              questions:
              - uuid: 95639f83-9600-4637-903a-c5b08d2f4e7c
                question_type: binary
                content: Voluptate repellat ut deserunt?
                choices:
                - answer: totam
                  correct: true
                - answer: est
                  correct: false
        '400':
          description: bad_request
          schema:
            type: object
            properties:
              subject:
                type: array
                items:
                  type: string
              lesson_uuid:
                type: array
                items:
                  type: string
              question_type:
                type: array
                items:
                  type: string
              question:
                type: array
                items:
                  type: string
              choices:
                type: array
                items:
                  type: string
          examples:
            application/json:
              choices:
              - size must be 2
  "/api/tests/{uuid}":
    get:
      summary: Retrieves a test
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        type: string
        required: true
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              uuid:
                type: string
              lesson_uuid:
                type: string
              title:
                type: string
              description:
                type: string
              questions:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    question_type:
                      type: string
                    content:
                      type: string
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          answer:
                            type: string
                          correct:
                            type: boolean
                        required:
                        - answer
                        - correct
                  required:
                  - uuid
                  - question_type
                  - content
                  - choices
            required:
            - uuid
            - lesson_uuid
            - title
            - description
            - questions
          examples:
            application/json:
              uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
              lesson_uuid: cf48df3b-ae86-464e-acd7-6cdca498fa8a
              title: Accusantium
              description: Similique aliquam voluptas quia.
              questions:
              - uuid: 95639f83-9600-4637-903a-c5b08d2f4e7c
                question_type: binary
                content: Voluptate repellat ut deserunt?
                choices:
                - answer: totam
                  correct: true
                - answer: est
                  correct: false
        '404':
          description: not_found
          schema:
            type: object
            properties:
              detail:
                type: string
            required:
            - detail
          examples:
            application/json:
              detail: Not found.
    put:
      summary: Updates a test
      tags:
      - Tests
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        type: string
        required: true
      - name: payload
        in: body
        schema:
          type: object
          properties:
            lesson_uuid:
              type: string
            title:
              type: string
            description:
              type: string
            questions:
              type: array
              items:
                type: object
                properties:
                  uuid:
                    type: string
                  _delete:
                    type: boolean
                  question_type:
                    type: string
                  content:
                    type: string
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        answer:
                          type: string
                        correct:
                          type: boolean
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              uuid:
                type: string
              lesson_uuid:
                type: string
              title:
                type: string
              description:
                type: string
              questions:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    question_type:
                      type: string
                    content:
                      type: string
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          answer:
                            type: string
                          correct:
                            type: boolean
                        required:
                        - answer
                        - correct
                  required:
                  - uuid
                  - question_type
                  - content
                  - choices
            required:
            - uuid
            - lesson_uuid
            - title
            - description
            - questions
          examples:
            application/json:
              uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
              lesson_uuid: cf48df3b-ae86-464e-acd7-6cdca498fa8a
              title: Accusantium
              description: Similique aliquam voluptas quia.
              questions:
              - uuid: 95639f83-9600-4637-903a-c5b08d2f4e7c
                question_type: binary
                content: Voluptate repellat ut deserunt?
                choices:
                - answer: totam
                  correct: true
                - answer: est
                  correct: false
        '400':
          description: bad_request
          schema:
            type: object
            properties:
              subject:
                type: array
                items:
                  type: string
              lesson_uuid:
                type: array
                items:
                  type: string
              question_type:
                type: array
                items:
                  type: string
              question:
                type: array
                items:
                  type: string
              choices:
                type: array
                items:
                  type: string
          examples:
            application/json:
              choices:
              - size must be 2
        '404':
          description: not_found
          schema:
            type: object
            properties:
              detail:
                type: string
            required:
            - detail
          examples:
            application/json:
              detail: Not found.
    delete:
      summary: Destroys a test
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        type: string
        required: true
      responses:
        '204':
          description: no_content
        '404':
          description: not_found
          schema:
            type: object
            properties:
              detail:
                type: string
            required:
            - detail
          examples:
            application/json:
              detail: Not found.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
