---
swagger: '2.0'
info:
  title: tests_api
  version: v1.0
paths:
  "/api/tests/":
    get:
      summary: Retrieves tests
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        type: integer
        required: false
        description: Number of results to return per page.
      - name: offset
        in: query
        type: integer
        required: false
        description: The initial index from which to return the results.
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                nullable: true
              previous:
                type: string
                nullable: true
              results:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    question_type:
                      type: string
                    subject:
                      type: string
                    question:
                      type: string
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          answer:
                            type: string
                          correct:
                            type: boolean
                  required:
                  - uuid
                  - subject
                  - question_type
                  - question
                  - choices
            required:
            - count
            - next
            - previous
            - results
          examples:
            application/json:
              count: 10
              next: 
              previous: 
              results:
              - uuid: cf48df3b-ae86-464e-acd7-6cdca498fa8a
                subject: veniam
                question_type: binary
                question: Et dignissimos voluptate ab?
                choices:
                - answer: numquam
                  correct: true
                - answer: porro
                  correct: false
    post:
      summary: Creates a test
      tags:
      - Tests
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: test
        in: body
        schema:
          type: object
          properties:
            uuid:
              type: string
            question_type:
              type: string
            subject:
              type: string
            question:
              type: string
            choices:
              type: array
              items:
                type: object
                properties:
                  answer:
                    type: string
                  correct:
                    type: boolean
          required:
          - uuid
          - subject
          - question_type
          - question
          - choices
      responses:
        '201':
          description: created
          schema:
            type: object
            properties:
              uuid:
                type: string
              question_type:
                type: string
              subject:
                type: string
              question:
                type: string
              choices:
                type: array
                items:
                  type: object
                  properties:
                    answer:
                      type: string
                    correct:
                      type: boolean
            required:
            - uuid
            - subject
            - question_type
            - question
            - choices
          examples:
            application/json:
              uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
              subject: accusantium
              question_type: binary
              question: Voluptate repellat ut deserunt?
              choices:
              - answer: totam
                correct: true
              - answer: est
                correct: false
        '400':
          description: bad_request
          schema:
            type: object
            properties:
              subject:
                type: array
                items:
                  type: string
              lesson_id:
                type: array
                items:
                  type: string
              question_type:
                type: array
                items:
                  type: string
              question:
                type: array
                items:
                  type: string
              choices:
                type: array
                items:
                  type: string
          examples:
            application/json:
              choices:
              - size must be 2
  "/api/tests/{uuid}":
    get:
      summary: Retrieves a test
      tags:
      - Tests
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        type: string
        required: true
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              uuid:
                type: string
              question_type:
                type: string
              subject:
                type: string
              question:
                type: string
              choices:
                type: array
                items:
                  type: object
                  properties:
                    answer:
                      type: string
                    correct:
                      type: boolean
            required:
            - uuid
            - subject
            - question_type
            - question
            - choices
          examples:
            application/json:
              uuid: 34fde577-2360-4dd9-8aa3-a0d32b799336
              subject: accusantium
              question_type: binary
              question: Voluptate repellat ut deserunt?
              choices:
              - answer: totam
                correct: true
              - answer: est
                correct: false
        '404':
          description: not_found
          schema:
            type: object
            properties:
              detail:
                type: string
            required:
            - detail
          examples:
            application/json:
              detail: Not found.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
