# Generated by Django 2.2.4 on 2020-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="url",
            field=models.URLField(blank=True, default="", max_length=300, verbose_name="URL"),
        ),
    ]
