# Generated by Django 2.2.10 on 2020-05-06 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0003_auto_20200430_0723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="pdf_file",
            field=models.FileField(
                upload_to="lesson",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
