name: CD Landing Page (test)
on:
  push:
    branches:
      # - master
      - '**'
#
jobs:
  build-and-deploy:
    name: Deploy landing to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: 0 # ${{ secrets.LANDING__HEROKU_OAUTH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore cache
      uses: actions/cache@v1
      id: landing-cache
      with:
        path: README.md
        key: ${{ runner.os }}-landing001-${{ hashFiles('landing/**') }}
        restore-keys: |
          ${{ runner.os }}-landing001-

    - run: ls -al
      if: steps.landing-cache.outputs.cache-hit != 'true'

    - run: echo ${{ steps.landing-cache.outputs.cache-hit }}

    # - name: Build docker
    #   run: |
    #     docker build -t registry.heroku.com/montelearn-landing/web .

    # - name: Login to Heroku Container registry
    #   run: heroku container:login

    # - name: Push container
    #   run: docker push registry.heroku.com/montelearn-landing/web

    # - name: Release container
    #   run: heroku container:release web --app montelearn-landing
