name: CD Landing Page (test)
on:
  push:
    branches:
      - master
    paths:
      - 'landing/**'
      - 'Dockerfile'
      - '!landing/tsconfig.eslint.json'
jobs:
  build-and-deploy:
    name: Deploy landing to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.LANDING__HEROKU_OAUTH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make env file
      run: |
        cat > landing/.env << EOF
        API_PLAYGROUND_URL=https://lesson-api-test.herokuapp.com
        EOF

    - name: Build docker
      run: docker build -t registry.heroku.com/montelearn-landing/web .

    - name: Login to Heroku Container registry
      run: heroku container:login

    - name: Push container
      run: docker push registry.heroku.com/montelearn-landing/web

    - name: Release container
      run: heroku container:release web --app montelearn-landing
