name: CD Landing Page (test)
on:
  push:
    branches:
      # - master
      - '**'

jobs:
  build-and-deploy:
    name: Deploy landing to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: 0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        DOCKER_BUILDKIT=1 docker build --target server \
        -t registry.heroku.com/montelearn-landing/web .

    # - name: Login to Heroku Container registry
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_OAUTH_TOKEN }}
    #   run: heroku container:login

    # - name: Push container
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_OAUTH_TOKEN }}
    #   run: docker push registry.heroku.com/montelearn-landing/web

    # - name: Release container
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_OAUTH_TOKEN }}
    #   run: heroku container:release web --app montelearn-landing
